import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { getFirestore, collection, getDocs } from "firebase/firestore/lite";
import { initFirebase } from "../db/index";

import { getAuth, signInWithEmailAndPassword, signOut } from "firebase/auth";
import { useRouter } from "next/router";
import { useState } from "react";
import Link from "next/link";
import ThreadPreview, { ThreadData } from "../components/Threads/ThreadPreview";
import SearchBar from "../components/SearchBar";
import PostPreview from "../components/Posts/PostPreview";
import ImportantThreadsContainer from "../components/Threads/ImportantThreadsContainer";

// const app = initFirebase();

// const db = getFirestore(app);

// const auth = getAuth(app);

// console.log("auth", auth);
// console.log("currUser", auth.currentUser);

async function getThreads(db: any) {
  const threadsCol = collection(db, "threads");
  const threadSnapshot = await getDocs(threadsCol);
  const threadList = threadSnapshot.docs.map((doc) => doc.data());
  console.log(threadList);
  return threadList;
}

// TODO: create login form [extract data from form and put into signInWithEmailAndPassword funcs and other for signup]
// TODO: create signup form
// TODO: create logout func

// getThreads(db);

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [burgerMenuIsVisible, setBurgerMenuIsVisible] = useState(false);
  const router = useRouter();
  console.log(router);
  // const handleSignOut = () => {
  //   signOut(auth)
  //     .then(() => {
  //       // Sign-out successful.
  //       router.push("/");
  //     })
  //     .catch((error) => {
  //       // An error happened.
  //       console.log(error);
  //     });
  // };

  return (
    <div className={styles.container}>
      <SearchBar placeholder="Search for threads..." />
      <ImportantThreadsContainer label={"Top 3"} content={"top"} />
      <ImportantThreadsContainer label={"Hot/Trending"} content={"trending"} />
      <PostPreview
        id="123"
        author="Doe"
        body="Lorem ipsum dilore..."
        comments={[]}
        date="13/13/13"
        downvotes={40}
        image=""
        isFeatured={true}
        isHotTrending={false}
        isTopThree={false}
        title="This is it. How to brainwash yourself."
        upvotes={4002}
        views={130420}
        categories={[
          "fast",
          "cars",
          "fast",
          "cars",
          "fast",
          "cars",
          "fast",
          "cars",
          "fast",
          "cars",
          "fast",
          "cars",
        ]}
      />
      <ThreadPreview
        id="123"
        posts={[]}
        author="Jane"
        date="32/23/23"
        isFeatured={false}
        isHotTrending={false}
        isTopThree={false}
        members={4020000}
        image="asd"
        title={"Welcome to the first thread"}
        categories={[
          "fast",
          "cars",
          "fast",
          "cars",
          "fast",
          "cars",
          "fast",
          "cars",
          "fast",
          "cars",
          "fast",
          "cars",
        ]}
      />
      <ThreadPreview
        id="124"
        posts={[]}
        author="Jane"
        date="32/23/23"
        isFeatured={true}
        isHotTrending={false}
        isTopThree={false}
        members={4020000000}
        image="asd"
        title={"Welcome to the first thread"}
        categories={["fast", "cars"]}
      />
    </div>

    // <>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <main className={styles.main}>
    //     <div className={styles.description}>
    //       <p>
    //         Get started by editing&nbsp;
    //         <code className={styles.code}>pages/index.tsx</code>
    //       </p>
    //       <div>
    //         <a
    //           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //           target="_blank"
    //           rel="noopener noreferrer"
    //         >
    //           By{' '}
    //           <Image
    //             src="/vercel.svg"
    //             alt="Vercel Logo"
    //             className={styles.vercelLogo}
    //             width={100}
    //             height={24}
    //             priority
    //           />
    //         </a>
    //       </div>
    //     </div>

    //     <div className={styles.center}>
    //       <Image
    //         className={styles.logo}
    //         src="/next.svg"
    //         alt="Next.js Logo"
    //         width={180}
    //         height={37}
    //         priority
    //       />
    //       <div className={styles.thirteen}>
    //         <Image
    //           src="/thirteen.svg"
    //           alt="13"
    //           width={40}
    //           height={31}
    //           priority
    //         />
    //       </div>
    //     </div>

    //     <div className={styles.grid}>
    //       <a
    //         href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2 className={inter.className}>
    //           Docs <span>-&gt;</span>
    //         </h2>
    //         <p className={inter.className}>
    //           Find in-depth information about Next.js features and&nbsp;API.
    //         </p>
    //       </a>

    //       <a
    //         href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2 className={inter.className}>
    //           Learn <span>-&gt;</span>
    //         </h2>
    //         <p className={inter.className}>
    //           Learn about Next.js in an interactive course with&nbsp;quizzes!
    //         </p>
    //       </a>

    //       <a
    //         href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2 className={inter.className}>
    //           Templates <span>-&gt;</span>
    //         </h2>
    //         <p className={inter.className}>
    //           Discover and deploy boilerplate example Next.js&nbsp;projects.
    //         </p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2 className={inter.className}>
    //           Deploy <span>-&gt;</span>
    //         </h2>
    //         <p className={inter.className}>
    //           Instantly deploy your Next.js site to a shareable URL
    //           with&nbsp;Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>
    // </>
  );
}
